"""Initial

Revision ID: 68a304d228f4
Revises: 
Create Date: 2024-08-12 16:24:54.311043

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68a304d228f4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('register_date', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('cipher',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cipher_message', sa.String(), nullable=False),
    sa.Column('key_cipher', sa.String(), nullable=False),
    sa.Column('pass_phrase', sa.String(), nullable=False),
    sa.Column('create_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('life_cipher', sa.Enum('one_hour', 'one_day', 'seven_days', name='lifecipher'), nullable=True),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cipher')
    op.drop_table('user')
    # ### end Alembic commands ###
